backend:
  name: git-gateway
  branch: master

media_folder: "/static/files/"
public_folder: "/files/"

collections:
  - name: "about"
    label: "About"
    folder: "src/pages/about"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Content Type", name: "contentType", widget: "hidden", default: "about"}
      - {label: "Path", name: "path", widget: "hidden", default: "/about"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
